export const SAVE_ACTIVITY = 'SAVE_ACTIVITY';
export const SAVE_ACTIVITY_FAILURE = 'SAVE_ACTIVITY_FAILURE';
export const SAVE_ACTIVITY_SUCCESS = 'SAVE_ACTIVITY_SUCCESS';

export const SAVE_ACTIVITY_TO_STORAGE = 'SAVE_ACTIVITY_TO_STORAGE';

export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const DELETE_ACTIVITY_FAILURE = 'DELETE_ACTIVITY_FAILURE';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';

export const SET_ACTIVITY_STORAGE = 'SET_ACTIVITY_STORAGE';


export const EDIT_ACTIVITY = 'EDIT_ACTIVITY';
export const EDIT_ACTIVITY_FAILURE = 'EDIT_ACTIVITY_FAILURE';
export const EDIT_ACTIVITY_SUCCESS = 'EDIT_ACTIVITY_SUCCESS';
